apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
      - name: auth-container
        image: benhassan98/auth-server-image
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-pod
  ports:
  - name: auth-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080
                                                                                                                                    
